export interface PetAvatarOption {
  id: string;
  name: string;
  creator: string;
  src: string;
  sourceUrl: string;
}

/**
 * Cinquante Pets Petdex choisis pour leur lien avec la cuisine, lisible même
 * dans les 44 px de l'avatar d'en-tête. La liste des identifiants est
 * dupliquée côté serveur (`PET_AVATAR_IDS`, authController.ts) : les deux
 * doivent rester synchronisées.
 */
export const PET_AVATARS: PetAvatarOption[] = [
  {
    id: 'boba',
    name: 'Boba',
    creator: 'railly',
    src: '/pets/avatars/boba.webp',
    sourceUrl: 'https://petdex.dev/pets/boba',
  },
  {
    id: 'carrot-bun',
    name: 'Carrot Bun',
    creator: 'Yang Singa',
    src: '/pets/avatars/carrot-bun.webp',
    sourceUrl: 'https://petdex.dev/pets/carrot-bun',
  },
  {
    id: 'croissant-cat',
    name: 'Croissant Cat',
    creator: 'Kris z.',
    src: '/pets/avatars/croissant-cat.webp',
    sourceUrl: 'https://petdex.dev/pets/croissant-cat',
  },
  {
    id: 'hei-mao-chef',
    name: 'Chef Cochon',
    creator: 'misonl',
    src: '/pets/avatars/hei-mao-chef.webp',
    sourceUrl: 'https://petdex.dev/pets/hei-mao-chef',
  },
  {
    id: 'milk-tea-koala',
    name: 'Koala Bubble Tea',
    creator: 'Wenxiang Z.',
    src: '/pets/avatars/milk-tea-koala.webp',
    sourceUrl: 'https://petdex.dev/pets/milk-tea-koala',
  },
  {
    id: 'sleepy-croissant',
    name: 'Croissant',
    creator: '羊',
    src: '/pets/avatars/sleepy-croissant.webp',
    sourceUrl: 'https://petdex.dev/pets/sleepy-croissant',
  },
  {
    id: 'bubble-tea',
    name: 'Bubble Tea',
    creator: 'Chun-Chao L.',
    src: '/pets/avatars/bubble-tea.webp',
    sourceUrl: 'https://petdex.dev/pets/boba-2',
  },
  {
    id: 'bun',
    name: 'Chat boulanger',
    creator: 'ριριlυ',
    src: '/pets/avatars/bun.webp',
    sourceUrl: 'https://petdex.dev/pets/bun',
  },
  {
    id: 'chefito',
    name: 'Chefito',
    creator: 'chefuri2',
    src: '/pets/avatars/chefito.webp',
    sourceUrl: 'https://petdex.dev/pets/chefito',
  },
  {
    id: 'sous-chef',
    name: 'Sous-chef',
    creator: 'chefuri2',
    src: '/pets/avatars/sous-chef.webp',
    sourceUrl: 'https://petdex.dev/pets/sous-chef',
  },
  {
    id: 'chef',
    name: 'Chef',
    creator: 'Heiko',
    src: '/pets/avatars/chef.webp',
    sourceUrl: 'https://petdex.dev/pets/chef-3',
  },
  {
    id: 'bagel',
    name: 'Bagel',
    creator: 'Suning D.',
    src: '/pets/avatars/bagel.webp',
    sourceUrl: 'https://petdex.dev/pets/bagel',
  },
  {
    id: 'banana',
    name: 'Banane',
    creator: 'Ali A.',
    src: '/pets/avatars/banana.webp',
    sourceUrl: 'https://petdex.dev/pets/banana',
  },
  {
    id: 'banana-cat',
    name: 'Chat banane',
    creator: 'ibreeze2017',
    src: '/pets/avatars/banana-cat.webp',
    sourceUrl: 'https://petdex.dev/pets/bananacat',
  },
  {
    id: 'biscuit',
    name: 'Biscuit',
    creator: 'jiaao w.',
    src: '/pets/avatars/biscuit.webp',
    sourceUrl: 'https://petdex.dev/pets/biscuit',
  },
  {
    id: 'boba-axolotl',
    name: 'Axolotl Boba',
    creator: 'Ted Tschopp',
    src: '/pets/avatars/boba-axolotl.webp',
    sourceUrl: 'https://petdex.dev/pets/blue-boba-axolotl',
  },
  {
    id: 'butter-bear',
    name: 'Ours au beurre',
    creator: 'shuang c.',
    src: '/pets/avatars/butter-bear.webp',
    sourceUrl: 'https://petdex.dev/pets/butter-bear',
  },
  {
    id: 'cheese',
    name: 'Fromage',
    creator: 'cy l.',
    src: '/pets/avatars/cheese.webp',
    sourceUrl: 'https://petdex.dev/pets/cheese',
  },
  {
    id: 'cheese-bear',
    name: 'Ours fromage',
    creator: 'ZHI SHI',
    src: '/pets/avatars/cheese-bear.webp',
    sourceUrl: 'https://petdex.dev/pets/cheese-bear',
  },
  {
    id: 'cherry',
    name: 'Cerise',
    creator: 'broccoli',
    src: '/pets/avatars/cherry.webp',
    sourceUrl: 'https://petdex.dev/pets/cherry',
  },
  {
    id: 'chick-peach',
    name: 'Poussin pêche',
    creator: 'computersniper',
    src: '/pets/avatars/chick-peach.webp',
    sourceUrl: 'https://petdex.dev/pets/chick-peach',
  },
  {
    id: 'chika-matcha',
    name: 'Chika Matcha',
    creator: 'boygotflames',
    src: '/pets/avatars/chika-matcha.webp',
    sourceUrl: 'https://petdex.dev/pets/chikamatcha',
  },
  {
    id: 'cookie-ann',
    name: 'Cookie Ann',
    creator: 'nor a x.',
    src: '/pets/avatars/cookie-ann.webp',
    sourceUrl: 'https://petdex.dev/pets/cookie-ann',
  },
  {
    id: 'cream-cat',
    name: 'Chat crème',
    creator: '塔塔',
    src: '/pets/avatars/cream-cat.webp',
    sourceUrl: 'https://petdex.dev/pets/cream-cat',
  },
  {
    id: 'cream-puff',
    name: 'Chou à la crème',
    creator: 'ash021',
    src: '/pets/avatars/cream-puff.webp',
    sourceUrl: 'https://petdex.dev/pets/cream-puff-2',
  },
  {
    id: 'cupcake-caticorn',
    name: 'Cupcake licorne',
    creator: 'Jiyun',
    src: '/pets/avatars/cupcake-caticorn.webp',
    sourceUrl: 'https://petdex.dev/pets/cupcake-caticorn-pet',
  },
  {
    id: 'devil-burger',
    name: 'Burger diable',
    creator: 'Holy Song',
    src: '/pets/avatars/devil-burger.webp',
    sourceUrl: 'https://petdex.dev/pets/devil-burger',
  },
  {
    id: 'honeybee',
    name: 'Abeille à miel',
    creator: 'ριριlυ',
    src: '/pets/avatars/honeybee.webp',
    sourceUrl: 'https://petdex.dev/pets/honeybee',
  },
  {
    id: 'ice-cream-cat',
    name: 'Chat glace',
    creator: 'Petdex seed',
    src: '/pets/avatars/ice-cream-cat.webp',
    sourceUrl: 'https://petdex.dev/pets/ice-cream-cat',
  },
  {
    id: 'jack-pepper',
    name: 'Jack Pepper',
    creator: 'justondra',
    src: '/pets/avatars/jack-pepper.webp',
    sourceUrl: 'https://petdex.dev/pets/jack-pepper',
  },
  {
    id: 'lemon',
    name: 'Citron',
    creator: 'shuyanliu6',
    src: '/pets/avatars/lemon.webp',
    sourceUrl: 'https://petdex.dev/pets/lemon',
  },
  {
    id: 'melon-star',
    name: 'Pastèque',
    creator: 'tonglei z.',
    src: '/pets/avatars/melon-star.webp',
    sourceUrl: 'https://petdex.dev/pets/melonstar',
  },
  {
    id: 'milk-tea-mouse',
    name: 'Souris thé au lait',
    creator: '忠良 齐.',
    src: '/pets/avatars/milk-tea-mouse.webp',
    sourceUrl: 'https://petdex.dev/pets/milk-tea-mouse',
  },
  {
    id: 'mochi',
    name: 'Mochi',
    creator: 'Aoi',
    src: '/pets/avatars/mochi.webp',
    sourceUrl: 'https://petdex.dev/pets/mochi',
  },
  {
    id: 'milk-mochi',
    name: 'Mochi au lait',
    creator: 'zion-zion-zion',
    src: '/pets/avatars/milk-mochi.webp',
    sourceUrl: 'https://petdex.dev/pets/mochi-milk',
  },
  {
    id: 'peach',
    name: 'Pêche',
    creator: 'ivbutsykin',
    src: '/pets/avatars/peach.webp',
    sourceUrl: 'https://petdex.dev/pets/peach',
  },
  {
    id: 'potato',
    name: 'Patate',
    creator: 'fang j.',
    src: '/pets/avatars/potato.webp',
    sourceUrl: 'https://petdex.dev/pets/potato',
  },
  {
    id: 'pudding',
    name: 'Pudding',
    creator: 'Summer Chen',
    src: '/pets/avatars/pudding.webp',
    sourceUrl: 'https://petdex.dev/pets/pudding',
  },
  {
    id: 'robocarrot',
    name: 'Carotte',
    creator: 'CosmosMount',
    src: '/pets/avatars/robocarrot.webp',
    sourceUrl: 'https://petdex.dev/pets/robocarrot',
  },
  {
    id: 'soda',
    name: 'Soda',
    creator: 'validatedev',
    src: '/pets/avatars/soda.webp',
    sourceUrl: 'https://petdex.dev/pets/soda',
  },
  {
    id: 'steamling',
    name: 'Petite vapeur',
    creator: 'DJONE',
    src: '/pets/avatars/steamling.webp',
    sourceUrl: 'https://petdex.dev/pets/steamling',
  },
  {
    id: 'strawberry',
    name: 'Fraise',
    creator: 'zwu528303-wq',
    src: '/pets/avatars/strawberry.webp',
    sourceUrl: 'https://petdex.dev/pets/strawwy',
  },
  {
    id: 'tarty',
    name: 'Tartelette',
    creator: '-7Kg',
    src: '/pets/avatars/tarty.webp',
    sourceUrl: 'https://petdex.dev/pets/tarty',
  },
  {
    id: 'curry-dog',
    name: 'Chien curry',
    creator: 'f1rst3h',
    src: '/pets/avatars/curry-dog.webp',
    sourceUrl: 'https://petdex.dev/pets/winter-curry-dog',
  },
  {
    id: 'mushrooms',
    name: 'Champignons',
    creator: 'ibreeze2017',
    src: '/pets/avatars/mushrooms.webp',
    sourceUrl: 'https://petdex.dev/pets/working-mushrooms',
  },
  {
    id: 'acorn-squirrel',
    name: 'Écureuil noisette',
    creator: 'sushi-song',
    src: '/pets/avatars/acorn-squirrel.webp',
    sourceUrl: 'https://petdex.dev/pets/acorn-squirrel',
  },
  {
    id: 'apple',
    name: 'Pomme',
    creator: 'wbtlbs',
    src: '/pets/avatars/apple.webp',
    sourceUrl: 'https://petdex.dev/pets/apple',
  },
  {
    id: 'blueberry',
    name: 'Myrtille',
    creator: 'au w.',
    src: '/pets/avatars/blueberry.webp',
    sourceUrl: 'https://petdex.dev/pets/blueberry',
  },
  {
    id: 'choco',
    name: 'Choco',
    creator: 'Faustina L.',
    src: '/pets/avatars/choco.webp',
    sourceUrl: 'https://petdex.dev/pets/choco',
  },
  {
    id: 'cocoa',
    name: 'Cacao',
    creator: 'hanlayaya',
    src: '/pets/avatars/cocoa.webp',
    sourceUrl: 'https://petdex.dev/pets/cocoa',
  },
];

export function getPetAvatar(id: string | null | undefined): PetAvatarOption | undefined {
  return PET_AVATARS.find((pet) => pet.id === id);
}
